server:
  port: 8084
spring:
  application:
    name: provider
eureka:
  instance:
    prefer-ip-address: true  #注册服务的时候使用服务的IP地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
      ##检索服务信息
    fetch-registry: true